### PR TITLE
network: bridge: don't recreate fake dev and log errors

### LINKED ISSUE #8: Failed to launch pod with network
I attached a bridge to a pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        bridge.network.kubevirt.io/mybridge: 1
```

but it fails with:

```
2018-02-19 21:44:02 +0100 CET   2018-02-19 21:44:02 +0100 CET   1         demo-pod.1514d4e22fea75ad   Pod       spec.containers{nginx}   Normal    Pulled    kubelet, minikube   Successfully pulled image "nginx:latest"
2018-02-19 21:44:02 +0100 CET   2018-02-19 21:44:02 +0100 CET   1         demo-pod.1514d4e234b0687f   Pod       spec.containers{nginx}   Normal    Created   kubelet, minikube   Created container
2018-02-19 21:44:02 +0100 CET   2018-02-19 21:44:02 +0100 CET   1         demo-pod.1514d4e237b96a1c   Pod       spec.containers{nginx}   Warning   Failed    kubelet, minikube   Error: failed to start container "nginx": Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/tmp/deviceplugin-network-bridge-fakedev": no such file or directory
```

I wonder where fakedev comes from.

### PR DESCRIPTION
**Pull request by phoracek**
This should help us to fix https://github.com/kubevirt/kubernetes-device-plugins/issues/8

### CODE REVIEW

File: pkg/network/bridge/plugin.go [hunk 1]
```diff
@@ -61,8 +62,12 @@ func newDevicePlugin(bridge string, nics []string) *NetworkBridgeDevicePlugin {
 	}
 	ret.DevicePlugin.Deps = ret
 
+	err := createFakeDevice()
+	if err != nil {
+		glog.Exitf("Failed to create fake device: %s", err)
+	}
+
 	// TODO: This should be triggered by start()
```
Comment (mpolednik) [inline pkg/network/bridge/plugin.go]: Still applies to the block above.

File: pkg/network/bridge/plugin.go [hunk 2]
```diff
@@ -80,10 +84,16 @@ func bridgeExists(bridge string) bool {
 	}
 }
 
-func createFakeDevice() {
-	glog.V(3).Info("Creating fake block device")
-	cmd := exec.Command("mknod", fakeDevicePath, "b", "1", "1")
-	cmd.Run()
+func createFakeDevice() error {
+	if _, err := os.Stat(fakeDevicePath); err == nil {
```
Comment (mpolednik) [inline pkg/network/bridge/plugin.go]: Extra: it might be worth checking os.IsNotExist(err); otherwise we'd warn about device already existing even if stat failed for other reason.
